# Generated by Django 4.2.1 on 2023-05-31 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_app', '0044_alter_batch_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('no_of_vacancy', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=6)),
                ('last_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.course')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Placement.job_title')),
            ],
        ),
    ]
