# Generated by Django 4.2.1 on 2023-05-18 04:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('student', models.CharField(max_length=255, verbose_name='Student:')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, verbose_name='Gender:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('alter_email', models.EmailField(blank=True, max_length=254, verbose_name='Alternative Email:')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address:')),
                ('alter_address', models.CharField(blank=True, max_length=255, verbose_name='Alternative Address:')),
                ('dob', models.DateField(verbose_name='Dop:')),
                ('mobile', models.CharField(blank=True, max_length=10, verbose_name='Mobile:')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street:')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City:')),
                ('pincode', models.CharField(blank=True, max_length=6, verbose_name='Pincode:')),
                ('whatapp', models.CharField(max_length=10, verbose_name='Whatsapp:')),
                ('EnquirySource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.enquirysource')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Employee_app.district', verbose_name='District:')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.state', verbose_name='State:')),
            ],
        ),
    ]
