# Generated by Django 4.2.1 on 2023-05-19 06:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_app', '0001_initial'),
        ('Student', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('student', models.CharField(max_length=255, verbose_name='Student:')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, verbose_name='Gender:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('alter_email', models.EmailField(blank=True, max_length=254, verbose_name='Alternative Email:')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address:')),
                ('alter_address', models.CharField(blank=True, max_length=255, verbose_name='Alternative Address:')),
                ('dob', models.DateField(verbose_name='Dop:')),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')], verbose_name='Mobile:')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street:')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City:')),
                ('pincode', models.CharField(blank=True, max_length=6, verbose_name='Pincode:')),
                ('whatapp', models.CharField(max_length=10, verbose_name='Whatsapp:')),
                ('collagename', models.CharField(max_length=255, verbose_name='Collage Name:')),
                ('yearofpass', models.PositiveIntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], verbose_name='Year of Pass')),
                ('rollno', models.CharField(max_length=255, verbose_name='Roll No')),
                ('registration', models.CharField(max_length=255, verbose_name='Registration Number:')),
                ('EnquirySource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.enquirysource')),
                ('district', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='Employee_app.district', verbose_name='District:')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.qualification', verbose_name='Qualification Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.state', verbose_name='State:')),
            ],
        ),
    ]
