# Generated by Django 4.2.1 on 2023-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
