# Generated by Django 4.2.1 on 2023-05-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0012_remove_cource_trainers'),
        ('Student', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.course'),
        ),
    ]
